language: php
php:
  - '7.0'
  - '5.6'
  - '5.4'

branches:
  only:
  - master
  - /^v.*$/

install:
  - npm install
  - npm install -g bower
  - bower install
  - composer install

script:
  - echo "assume script is successful"

before_deploy: npm run build

deploy:
  provider: releases
  file:
    - xhprof-viewer.tar.gz
    - xhprof-viewer.zip
  skip_cleanup: true
  api-key:
    secure: "CKD7oFN5iYDHpfB/sO86AeID5B9nipJCWywAA5vTiEHehsBNTJQ7x02e97lT0jmgLRVJHowcWixWKr/f8H2SN2xZ8bakN263fZFsuN23qjjPzyqUw0VzUedU9lLf17EF7WnDRdxf1wRHF13BUZz8YMqekqUZCt8tAF7D26Ncz2AeNHBZzZENH0EoYOZot1DXJA603OsA+Xb5vC4/0YcwgzWAj+yRETP69eDpJb4HG/t1jYsfSbpnkFau/CLtv6M3EYXq1VLcXCn3qg3dUat3IW0aczhb2R0+SNMtwv8hyc1D42EKOp1lCayEWG+kN67l98fmby0jQfV2g1ZOaP/5wELR9/wnCzo3dXBe7D24BxVryDF+/ihEV1vWRWgwzCJ7vmS86NCFH1z0IVM3Jpl/qtDs9qv+jTMtO2BLROFAiO5r0jwUM5BOgEoqk1VGWPuAe4poAlEXP3v6Ag6wzQPmLmDylZE9BoMWVfwxHRQf3oITJlPgwfNQlRoJCFQcb/wyfNZPAalSxcW8OPsztG9DDTxjL7yevUep+u4fLpOxY6qUEawBDYkzjfkKBYirA/WSONSsrlwh88x4NLxtLVmUofH3rRxF9VxomXt+z8aJpi4Msl+3iLB3wNJT2/ZVqMtf3Nev6G3mr7mRRMXIEWmWnrUdykELGhElhYqjzGadfXg="
  on:
    tags: true
    php: 5.6
